name: PHP Composer

on:
  push:
    branches: [ "DEV" ]
  pull_request:
    branches: [ "DEV" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    #environment: ENV-DEV-MandirForms
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  DEV-CICD-Deploy:
    name: DEV-CICD-Deploy
    environment: ENV-DEV-MandirForms
    runs-on: ubuntu-latest
    needs:
      - build
    if: needs.build.result == 'success'
    
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
  
          # Fetch all history for all tags and branches
          fetch-depth: 0
  
          # Checkout a specific branch
          ref: DEV
  
      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
  
          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.FTP_Host }}
          remote-user: ${{ secrets.FTP_Username }}
          remote-password: ${{ secrets.FTP_Password }}
  
          # Path for specific folder on server for files deployment
          remote-path: '/home/u847347078/domains/mediumslateblue-hedgehog-527643.hostingersite.com/public_html/dev'
  
          # Port for SFTP access to server
          remote-port: 21
