name: PHP Composer

on:
  push:
    branches: [ "UAT" ]
  pull_request:
    branches: [ "UAT" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    #environment: ENV-UAT-MandirForms
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    #- name: Build
    #  run: npm run build # The build command of your project
    
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       #==============
    #- uses: actions/checkout@v2
          
    #- name: SFTP Deploy
    #  uses: wlixcc/SFTP-Deploy-Action@v1.2.1
    #  with:
    #    username: 'u847347078'
    #    server: '62.72.28.94'
    #    port: 21 # default is 22
    #    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

        
    #    # will put all file under this path
    #    local_path: './*' # default is ./*
    #    # files will copy to under remote_path
    #    remote_path: '/home/u847347078/domains/mediumslateblue-hedgehog-527643.hostingersite.com/public_html/git_cicd'
        
    #    # sftp args
    #    args: '-o ConnectTimeout=5'
    #=========================================================

  UAT-CICD-Deploy:
    name: UAT-CICD-Deploy
    #environment: ENV-UAT-MandirForms
    runs-on: ubuntu-latest
    needs:
      - build
    if: needs.build.result == 'success'
    
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
  
          # Fetch all history for all tags and branches
          fetch-depth: 0
  
          # Checkout a specific branch
          ref: UAT
  
      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
  
          # Credentials for SFTP access to server using GitHub secrets
          remote-host: '62.72.28.94'
          remote-user: 'u847347078'
          remote-password: '=;3Y[Amc2+36'
  
          # Path for specific folder on server for files deployment
          remote-path: '/home/u847347078/domains/mediumslateblue-hedgehog-527643.hostingersite.com/public_html/git_cicd'
  
          # Port for SFTP access to server
          remote-port: 21
